name: conda-slicemypdf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - ipykernel
  - delegator
  - lxml
  - pdfminer
  - pip:
    - xmltodict
    - PyYAML
    - wand
    - zipfile36
